name: Run Tests on Docker container (Playwright)
on:
  push:
    branches: [dev]
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
permissions:
  contents: write
jobs:
  checkout:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        id: install-dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

    # - name: Install Playwright Browsers
    #   id: install-playwright-browsers
    #   if: steps.cache-playwright.outputs.cache-hit != 'true'
    #   run: npx playwright install --with-deps
  test:
    needs: checkout
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            /usr/local/bin/docker
          key: ${{ runner.os }}-npm-${{ hashFiles('**/*.lock') }}

      # build Docker image and run tests
      - name: Build image and test
        continue-on-error: true
        run: |
          chmod +x ./scripts/docker_build_and_run.sh
          npm run docker:run

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: |
            ./report
            ./test-results
          retention-days: 30
          if-no-files-found: ignore

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: history
          allure_results: report/allure-results

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
